### ISSUE TITLE
For Version 0.2

### ISSUE THREAD

**Issue by tiannian** [FindoraNetwork/abcf#51]
Add optimizations for abcf.

## TODO
- [ ] #30 
- [ ] Auto declare storage.
- [x] Define merkle algo for special field.
- [x] add module call macros.
- [x] Impl manager's new in trait without in bare code.
- [x] Add `Call` in macros.
- [x] Extend CallEntry as inner EventBus.
- [ ] Add multi-thread support.
- [x] Add returnable support for module call.

**Comment by tiannian** [comment]
Some feature will implement at next version
